# -*- coding: utf-8 -*-
"""ИИ классификаторы.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16cIYlFClPLe6heFVJ6pQl-9u5POMo6NB
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
sns.set_palette('husl')
import matplotlib.pyplot as plt
# %matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder, StandardScaler

import gdown

#https://www.kaggle.com/datasets/resulcaliskan/diamonds?resource=download

file_id = "11W9D8NrZ0vQSh4tMEjZSIPFJ-XZhpJFY"  # ID файла
gdown.download(f'https://drive.google.com/uc?id={file_id}', 'diamonds.csv', quiet=False)

date = pd.read_csv('/content/diamonds.csv', nrows=1000) # оставлю только 1000 значений, 50к много

date.shape # размер датасета

date.head(10)

df = date.drop(['color', 'clarity'], axis=1)

import mpl_toolkits.mplot3d
from sklearn import datasets
from sklearn.cluster import KMeans

df.info()

df.describe()

df['cut'].unique()

df['cut'].value_counts()

sns.violinplot(y='cut', x='carat', data=df, inner='quartile')
plt.show()
sns.violinplot(y='cut', x='depth', data=df, inner='quartile')
plt.show()
sns.violinplot(y='cut', x='price', data=df, inner='quartile')
plt.show()
sns.violinplot(y='cut', x='table', data=df, inner='quartile')
plt.show()

sns.pairplot(df, hue='cut', markers='*')
plt.show()

plt.figure(figsize=(7,5))
sns.heatmap(df.corr(numeric_only = True), annot=True)
plt.show()

X = df.drop(['cut'], axis=1)
y = df['cut']
print(f'X shape: {X.shape} | y shape: {y.shape} ')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=10)

import scipy.stats as stats

y_mapped = y.map({'Ideal': 0, 'Premium': 1, 'Very Good': 2, 'Good': 3, 'Fair': 4})

X_train, X_test, y_train, y_test = train_test_split(X, y_mapped, test_size=0.50, shuffle=True)

stats.ttest_ind (a=y_train, b=y_test)

# создаем лист для тех моделей, которые будем изучать
models = []
models.append(('LR', LogisticRegression(solver='liblinear', max_iter=1000)))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVC', SVC(gamma='auto')))

# оцениваем их метрики
results = []
model_names = []

for name, model in models:
  kfold = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
  cv_results = cross_val_score(model, X_train, y_train, cv=kfold, scoring='accuracy')
  results.append(cv_results)
  model_names.append(name)
  print('%s: %f (%f)' % (name, cv_results.mean(), cv_results.std()))

sk_lda = LinearDiscriminantAnalysis(solver='eigen')
sk_lda.fit(X_train, y_train)
sk_lda_pred_res = sk_lda.predict(X_test)
sk_transformed = sk_lda.transform(X_train)
sk_lda_accuracy = accuracy_score(y_test, sk_lda_pred_res)

print(f'sk LDA accuracy: {sk_lda_accuracy}')
print(f'sk LDA prediction: {sk_lda_pred_res}')
print('sk transformed features', sk_transformed[:5].T, sep='\n')

from mlxtend.plotting import plot_decision_regions

y_s = y_train
X_2d= X_train[['carat',	'depth']].values

y_2d = y_s.values


sk_lda1 = LinearDiscriminantAnalysis(solver='eigen')
sk_lda1.fit(X_2d, y_2d)

plt.title('LDA surface with original features')
plot_decision_regions(
    	X=X_2d,
    	y=y_2d,
    	clf=sk_lda1)

dataset = df["cut"].map({'Ideal': 0, 'Premium': 1, 'Very Good': 2, 'Good': 3, 'Fair': 4})

Xs = df[['carat',	'depth']]
ys = dataset.values

sk_lda2 = LinearDiscriminantAnalysis(solver='eigen', n_components=2)
X1_lda = sk_lda2.fit(X, ys).transform(X)

Xs = X1_lda

X1_lda_train, X1_lda_test, y1_train, y1_test = train_test_split(X1_lda, ys, random_state=0)

sk_lda2.fit(X1_lda_train, y1_train)

plt.title('LDA surface with transformed features')
plot_decision_regions(X=X1_lda, y=ys, clf=sk_lda2)

predicted = sk_lda2.predict(X1_lda_test)

from sklearn import model_selection, preprocessing, feature_selection, ensemble, linear_model, metrics, decomposition

## Accuray e AUC
'''
Теперь смотрим метрики.
НА ТЕСТОВОМ ДАТАСЕТЕ
'''
accuracy = metrics.accuracy_score(y1_test, predicted)#Оценим точность классификации.

'''
Получим результат
'''

## Precision e Recall
recall = metrics.recall_score(y1_test, predicted, average="weighted")
precision = metrics.precision_score(y1_test, predicted, average="weighted")
print("Recall (all 1s predicted right):", round(recall,2))
print("Precision (confidence when predicting a 1):", round(precision,2))
print("Detail:")
print(metrics.classification_report(y1_test, predicted, target_names=[str(i) for i in np.unique(y_test)]))