# -*- coding: utf-8 -*-
"""ИИ регрессия.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UVMy_3IdBtdrEeF1AspGEWE8Gk-tLZaL
"""

from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.model_selection import cross_val_score

from sklearn import metrics
from collections import Counter

# сразу напишем код функции, которая будет вычислять все нужные метрики

def Reg_Models_Evaluation_Metrics (model,X_train,y_train,X_test,y_test,y_pred):
    cv_score = cross_val_score(estimator = model, X = X_train, y = y_train, cv = 10)

    # Calculating Adjusted R-squared
    r2 = model.score(X_test, y_test)
    # Number of observations is the shape along axis 0
    n = X_test.shape[0]
    # Number of features (predictors, p) is the shape along axis 1
    p = X_test.shape[1]
    # Adjusted R-squared formula
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    RMSE = np.sqrt(metrics.mean_squared_error(y_test, y_pred))
    R2 = model.score(X_test, y_test)
    CV_R2 = cv_score.mean()

    print(f'RMSE:  {round(RMSE,4)}\n  R2: {round(R2,4)}\n Adjusted R2: {round(adjusted_r2, 4)}\n Cross Validated R2: {round(cv_score.mean(),4)}')
    return R2, adjusted_r2, CV_R2, RMSE

# импорт нужных библиотек
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

import gdown

#https://www.kaggle.com/datasets/resulcaliskan/diamonds?resource=download

file_id = "11W9D8NrZ0vQSh4tMEjZSIPFJ-XZhpJFY"  # ID файла
gdown.download(f'https://drive.google.com/uc?id={file_id}', 'diamonds.csv', quiet=False)

df = pd.read_csv('/content/diamonds.csv') # оставлю только 1000 значений

df.shape # размер датасета

df.info()

df.describe()

"""# **ДИАГРАММЫ РАССЕЯНИЯ**"""

# Целевая переменная
target = 'price'

# Числовые признаки для визуализации
numeric_features = ['carat', 'depth', 'table', 'x', 'y', 'z']

# Построение графиков
for feature_name in numeric_features:
    plt.figure(figsize=(5, 4))
    plt.scatter(df[feature_name], df[target], alpha=0.5)
    plt.ylabel('price', size=12)
    plt.xlabel(feature_name, size=12)
    plt.tight_layout()
    plt.show()

"""# **ЛИНЕЙНАЯ РЕГРЕССИЯ**

**Создание и обучение модели**
"""

# Разделение на признаки (X) и целевую переменную (y)
X = df.drop(['price'], axis=1)
y = df['price']

print(f'X shape: {X.shape} | y shape: {y.shape}')

X = df[['carat', 'depth', 'table', 'x', 'y', 'z']]
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=10)

# создание и обучение модели
modelLR = LinearRegression()
modelLR.fit(X_train, y_train)

# предсказание
y_pr_LR = modelLR.predict(X_test)

_ = Reg_Models_Evaluation_Metrics(modelLR, X_train, y_train, X_test, y_test, y_pr_LR)

"""**Визуализация**"""

# Для diamonds: зависимость цены от carat
X2 = df['carat'].values[:, np.newaxis] # признак
y2 = df['price'].values # целевая переменная

model2 = LinearRegression()
model2.fit(X2, y2)

plt.scatter(X2, y2, color='g', alpha=0.5)
plt.plot(X2, model2.predict(X2), color='k', linewidth=2)
plt.ylabel('price', size=12)
plt.xlabel('carat', size=12)
plt.show()

"""# **Полиномиальная регрессия**"""

from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=3, include_bias=False)

poly_features = poly.fit_transform(X)
X_p_train, X_p_test, y_p_train, y_p_test = train_test_split(poly_features, y, test_size=0.3, random_state=42)

# Create a linear regression model
modelPR = LinearRegression()

# Fit the model to the data
modelPR.fit(X_p_train, y_p_train)

# Predict the response for a new data point
y_pr_PR = modelPR.predict(X_p_test)

_ = Reg_Models_Evaluation_Metrics(modelPR, X_p_train, y_p_train, X_p_test, y_p_test, y_pr_PR)

"""**Визуализация**"""

X2 = df['carat'].values[:, np.newaxis] # признак
y2 = df['price'].values # целевая переменная

poly_features = poly.fit_transform(X2)

model2 = LinearRegression()
model2.fit(poly_features, y2)


plt.scatter(X2, y2,color='g')
plt.plot(X2, model2.predict(poly.fit_transform(X2)),color='b')
plt.ylabel('price', size=12)
plt.xlabel('carat', size=12)
plt.show()

"""# **Регрессия дерева принятия решений**"""

from sklearn.tree import DecisionTreeRegressor

# Create a stepwise regression model
modelDT = DecisionTreeRegressor()

# Fit the model to the data
modelDT.fit(X_train, y_train)

# Predict the response for a new data point
y_dt_pred = modelDT.predict(X_test)

_ = Reg_Models_Evaluation_Metrics(modelDT, X_train, y_train, X_test, y_test, y_dt_pred)

"""# **Регрессия случайного леса**"""

from sklearn.ensemble import RandomForestRegressor

# Create a stepwise regression model
modelRF = RandomForestRegressor(n_estimators=100)

# Fit the model to the data
modelRF.fit(X_train, y_train)

# Predict the response for a new data point
y_rf_pred = modelRF.predict(X_test)

_ = Reg_Models_Evaluation_Metrics(modelRF, X_train, y_train, X_test, y_test, y_rf_pred)

"""# **Регрессия опорных векторов (SVR)**

параметры SVR:
*   epsilon - игнорирует ошибки меньше этого значения.
*   C - контролирует, насколько модель "старается" попасть в каждую точку.
*   max_iter - Максимум итераций
*   tol - Допустимая погрешность

**Линейное ядро**
"""

from sklearn.svm import SVR

modelSVR = SVR(kernel='linear',
               max_iter=1000,  # Ограничить итерации
               )

modelSVR.fit(X_train, y_train)

# Predict the response for a new data point
y_rf_pred = modelSVR.predict(X_test)


_ = Reg_Models_Evaluation_Metrics(modelSVR, X_train, y_train, X_test, y_test, y_rf_pred)

"""**Визуализация**"""

plt.scatter(X_train["carat"], y_train, color='darkorange',
            label='data')
plt.plot(X_train["carat"], modelSVR.predict(X_train), color='cornflowerblue',
         label='prediction')
plt.legend()
plt.show()

"""**Полиномиальное ядро**"""

from sklearn.svm import SVR

modelSVR = SVR(kernel='poly',
               max_iter=1000,  # Ограничить итерации
               )

modelSVR.fit(X_train, y_train)

y_rf_pred = modelSVR.predict(X_test)

_ = Reg_Models_Evaluation_Metrics(modelSVR, X_train, y_train, X_test, y_test, y_rf_pred)

"""**Визуализация**"""

plt.scatter(X_train["carat"], y_train, color='darkorange',
            label='data')
plt.plot(X_train["carat"], modelSVR.predict(X_train), color='cornflowerblue',
         label='prediction')
plt.legend()
plt.show()

"""# **Регрессия ElasticNet**"""

from sklearn.linear_model import ElasticNet

# Create an elastic net regression model
modelEN = ElasticNet(alpha=0.1, l1_ratio=0.8)

# Fit the model to the data
modelEN.fit(X_train, y_train)

# Predict the response for a new data point
y_en_pred = modelEN.predict(X_test)

_ = Reg_Models_Evaluation_Metrics(modelEN, X_train, y_train, X_test, y_test, y_en_pred)