# -*- coding: utf-8 -*-
"""ИИ кластеризация.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w1UOeIKc-nLPtT1XPO_0cYuhJcIeM0tg

# **Подготовка датасета**
"""

# Commented out IPython magic to ensure Python compatibility.
# Импортируем библиотеки

import numpy as np
import pandas as pd
import seaborn as sns
sns.set_palette('husl')
import matplotlib.pyplot as plt
# %matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings('ignore')

import gdown

#https://www.kaggle.com/datasets/resulcaliskan/diamonds?resource=download

file_id = "11W9D8NrZ0vQSh4tMEjZSIPFJ-XZhpJFY"  # ID файла
gdown.download(f'https://drive.google.com/uc?id={file_id}', 'diamonds.csv', quiet=False)

dataset = pd.read_csv('/content/diamonds.csv')

dataset_shuffled = dataset.sample(n=1000, random_state=42)
# перемешиваем датасет и берем только 1000 значений

dtt = dataset_shuffled

vals = dtt["cut"].unique()
vals

# сохраняем только числовые столбцы. Категориальные кодируем в числовые. Целевую переменную (если она есть) - убираем
cols_for_clusters = ['carat',	'depth',	'table',	'x', 'y', 'z', 'price']

df= dtt[cols_for_clusters].copy() # делаем копию, чтобы не было сюрпризов с исходным набором данных

df.head()

df.info()

X = df

# Создаем y для выборки (1000 строк), а не для всего датасета
y = dtt["cut"].replace(vals, [0, 1, 2, 3, 4])

# Добавляем масштабирование для иерархической кластеризации
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""# **K-Means**"""

import mpl_toolkits.mplot3d  # noqa: F401
from sklearn.cluster import KMeans

"""carat	depth	table	x	y	z

'Ideal', 'Premium', 'Good', 'Very Good', 'Fair'
"""

estimators = [
    ("k_means_diamonds_8", KMeans(n_clusters=8, random_state=42, n_init=10)),
    ("k_means_diamonds_3", KMeans(n_clusters=3, random_state=42, n_init=10)),
    ("k_means_diamonds_bad", KMeans(n_clusters=3, random_state=42, n_init=1, init="random")),
]

fig = plt.figure(figsize=(10, 8))
titles = ["8 кластеров", "3 кластера", "3 кластера, плохая инициализация"]

for idx, ((name, est), title) in enumerate(zip(estimators, titles)):
    ax = fig.add_subplot(2, 2, idx + 1, projection="3d", elev=48, azim=134)
    est.fit(X)
    labels = est.labels_
    ax.scatter(X['carat'], X['depth'], X['price'],
               c=labels.astype(float),
               cmap='viridis',
               edgecolor='k',
               alpha=0.6,
               s=20)

    ax.set_xlabel("Carat")
    ax.set_ylabel("Depth")
    ax.set_zlabel("Price")
    ax.set_title(title)

    ax.set_xticklabels([])
    ax.set_yticklabels([])
    ax.set_zticklabels([])

# кластеризация по ценовым диапазонам
ax = fig.add_subplot(2, 2, 4, projection="3d", elev=48, azim=134)

price_ranges = [
    (df['price'] < 1000, "Низкая (меньше 1000)"),
    ((df['price'] >= 1000) & (df['price'] < 3000), "Средняя (1000-3000)"),
    (df['price'] >= 3000, "Высокая (больше 3000)")
]

colors = ['red', 'green', 'blue']
for (mask, label), color in zip(price_ranges, colors):
    ds = df[mask]
    if len(ds) > 0:
        ax.scatter(ds['carat'], ds['depth'], ds['price'],
                   c=color,
                   label=label,
                   edgecolor='k',
                   alpha=0.5,
                   s=20)

ax.set_xlabel("Carat")
ax.set_ylabel("Depth")
ax.set_zlabel("Price")
ax.set_title("Группировка по цене")
ax.legend(loc='upper left', fontsize=8)

ax.set_xticklabels([])
ax.set_yticklabels([])
ax.set_zticklabels([])

plt.subplots_adjust(wspace=0.3, hspace=0.3)
plt.show()

"""# **Метрики**"""

from sklearn import metrics
from sklearn.metrics.cluster import adjusted_rand_score
n_clusters = np.arange(2, 21)

best_metric = [0, 10000, 0, []]

silhouette_score_values = []
adjusted_rand_score_values = []

for n in n_clusters:

    clusterer = KMeans(n_clusters=n, max_iter=10, n_init=10, random_state=42)
    clusterer.fit(X)
    y_pred = clusterer.predict(X)

    score1 = metrics.silhouette_score(X, y_pred)
    silhouette_score_values.append(score1)

    score2 = metrics.adjusted_rand_score(y, y_pred)
    adjusted_rand_score_values.append(score2)

    if score1 < best_metric[1] and score2 > best_metric[2]:
        best_metric[1] = score1
        best_metric[2] = score2
        best_metric[3] = clusterer.cluster_centers_
        best_metric[0] = n

best_metric

plt.figure(figsize=(9, 6))
plt.plot(n_clusters, silhouette_score_values, linewidth=3, label='Silhouette score')
plt.plot(n_clusters, adjusted_rand_score_values, linewidth=3, label='Adjusted rand score')
plt.xlabel('Number of clusters', size=16)
plt.ylabel('Score', size=16)
plt.xticks(n_clusters, size=16)
plt.yticks(size=16)
plt.legend(loc='best', fontsize=16)

plt.show()

"""# **Иерархическая кластеризация**"""

from scipy.cluster.hierarchy import linkage, dendrogram

n_samples = 1000
sample_idx = np.random.choice(len(X_scaled), n_samples, replace=False)
X_sample = X_scaled[sample_idx]

mergings = linkage(X_sample, method='ward')

# Визуализация
plt.figure(figsize=(15, 8))
dendrogram(mergings,
           leaf_rotation=90,
           leaf_font_size=6,
           truncate_mode='lastp',  # Показывать только последние p кластеров
           p=30)

plt.show()

"""# **Алгоритм DBSCAN**"""

from sklearn.cluster import DBSCAN
from sklearn import metrics
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn import datasets

mins = X.shape[1]

X_scaled_df = pd.DataFrame(X_scaled, columns=cols_for_clusters)

db = DBSCAN(eps=1.5, min_samples=4).fit(X_scaled)
core_samples_mask = np.zeros_like(db.labels_, dtype=bool)
core_samples_mask[db.core_sample_indices_] = True
labels = db.labels_

# Number of clusters in labels, ignoring noise if present.
n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)

# Plot result
plt.figure(figsize=(10, 6))

# Black removed and is used for noise instead.
unique_labels = set(labels)
colors = ['y', 'b', 'g', 'r']
print(colors)
for k, col in zip(unique_labels, colors):
    if k == -1:
        # Black used for noise.
        col = 'k'

    class_member_mask = (labels == k)

    xy = X_scaled_df[class_member_mask & core_samples_mask]
    plt.plot(xy["carat"], xy["depth"], 'o', markerfacecolor=col,
             markeredgecolor='k',
             markersize=6)

    xy = X_scaled_df[class_member_mask & ~core_samples_mask]
    plt.plot(xy["carat"], xy["depth"], 'o', markerfacecolor=col,
             markeredgecolor='k',
             markersize=6)

plt.title('number of clusters: %d' % n_clusters_)
plt.show()

features = ['carat', 'depth', 'price']

fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(1, 1, 1, projection="3d", elev=48, azim=134)

ax.scatter(X_scaled_df["carat"], X_scaled_df["depth"], X_scaled_df["price"],
           c=labels.astype(float), edgecolor="k")

ax.xaxis.set_ticklabels([])
ax.yaxis.set_ticklabels([])
ax.zaxis.set_ticklabels([])
ax.set_xlabel("carat")
ax.set_ylabel("depth")
ax.set_zlabel("price")
ax.set_title("DBSCAN")

plt.show()

"""# **Оценка алгоритмов кластеризации**"""

# evaluation metrics
sc = metrics.silhouette_score(X_scaled, labels)
print("Silhouette Coefficient:%0.2f" % sc)
ari = adjusted_rand_score(y, labels)
print("Adjusted Rand Index: %0.2f" % ari)

"""ARI получился низкий, потому что: характеристики алмазов (carat, price, размеры) слабо связаны с качеством огранки, два алмаза с огранкой "Ideal" могут стоить 500 и 5000"""