# -*- coding: utf-8 -*-
"""ИИ снижение размерности.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13T2M9PAw8p-TZl9JKl7gG_ErvrQeOss5

# **Подготовка датасета**
"""

# Commented out IPython magic to ensure Python compatibility.
# Импортируем библиотеки

import numpy as np
import pandas as pd
import seaborn as sns
sns.set_palette('husl')
import matplotlib.pyplot as plt
# %matplotlib inline
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

import gdown

#https://www.kaggle.com/datasets/resulcaliskan/diamonds?resource=download

file_id = "11W9D8NrZ0vQSh4tMEjZSIPFJ-XZhpJFY"  # ID файла
gdown.download(f'https://drive.google.com/uc?id={file_id}', 'diamonds.csv', quiet=False)

dataset = pd.read_csv('/content/diamonds.csv')

dataset_shuffled = dataset.sample(n=5000, random_state=42)
# перемешиваем датасет и берем только 5000 значений

dtt = dataset_shuffled

vals = dtt["cut"].unique()
vals

cols_for_clusters = ['carat',	'depth',	'table',	'x', 'y', 'z', 'price']

df= dtt[cols_for_clusters].copy()

X = df
y = dtt["cut"].replace(vals, [0, 1, 2, 3, 4])
yvals = dtt["cut"]

"""# **Метод главных компонентов**"""

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_new = pca.fit(X).transform(X)


plt.figure(figsize=(12,8))
colors = ["navy", "turquoise", "darkorange"]
lw = 2

for color, i, target_name in zip(colors, [0, 1, 2], cols_for_clusters):
    plt.scatter(
        X_new[y == i, 0], X_new[y == i, 1], color=color, alpha=0.8, lw=lw, label=vals[i]
    )

plt.legend(loc="best", shadow=False, scatterpoints=1)
plt.xlabel("z1")
plt.ylabel("z2")
plt.show()

pca.explained_variance_ratio_

"""первые главные компоненты сохраняют 99% дисперсии, вторые главные компоненты сохраняют только 3.2e-07% дисперсии

**Применение ICA**
"""

from sklearn.decomposition import FastICA

fast_ica = FastICA(n_components=2)
X_new = fast_ica.fit_transform(X)

plt.figure(figsize=(12,8))
colors = ["navy", "turquoise", "darkorange"]
lw = 2

for color, i, target_name in zip(colors, [0, 1, 2], cols_for_clusters):
    plt.scatter(
        X_new[y == i, 0], X_new[y == i, 1], color=color, alpha=0.8, lw=lw, label=vals[i]
    )

plt.legend(loc="best", shadow=False, scatterpoints=1)
plt.xlabel("z1")
plt.ylabel("z2")
plt.show()

"""# **Kernel PCA**"""

from sklearn.decomposition import KernelPCA

rbf_pca = KernelPCA(n_components=2, kernel='rbf', gamma=0.04)
X_new = rbf_pca.fit_transform(X)

plt.figure(figsize=(12,8))
colors = ["navy", "turquoise", "darkorange"]
lw = 2

for color, i, target_name in zip(colors, [0, 1, 2], cols_for_clusters):
    plt.scatter(
        X_new[y == i, 0], X_new[y == i, 1], color=color, alpha=0.8, lw=lw, label=vals[i]
    )

plt.legend(loc="best", shadow=False, scatterpoints=1)
plt.xlabel("z1")
plt.ylabel("z2")
plt.show()

"""# **tSNE**"""

from sklearn.manifold import TSNE

tsne = TSNE(n_components=2)
X_new = tsne.fit_transform(X)

# Вывод результатов
print('Initial Shape of X: ', X.shape)
print('New Shape of X: ', X_new.shape)
print('Kullback-Leibler divergence after optimization: ', tsne.kl_divergence_)
print('No. of iterations: ', tsne.n_iter_)
#print('Embedding vectors: ', tsne.embedding_)

plt.figure(figsize=(12,8))
colors = ["navy", "turquoise", "darkorange"]
lw = 2

for color, i, target_name in zip(colors, [0, 1, 2], cols_for_clusters):
    plt.scatter(
        X_new[y == i, 0], X_new[y == i, 1], color=color, alpha=0.8, lw=lw, label=vals[i]
    )

plt.legend(loc="best", shadow=False, scatterpoints=1)
plt.xlabel("z1")
plt.ylabel("z2")
plt.show()

"""# **DBSCAN для кластеризации**"""

from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score
from sklearn.metrics import v_measure_score
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

dbscan_cluster1 = DBSCAN(eps = 0.7, min_samples = 5)
X_new = dbscan_cluster1.fit(X_scaled)

# Number of Clusters
labels=dbscan_cluster1.labels_
N_clus=len(set(labels))-(1 if -1 in labels else 0)
print('Estimated no. of clusters: %d' % N_clus)

# Identify Noise
n_noise = list(dbscan_cluster1.labels_).count(-1)
print('Estimated no. of noise points: %d' % n_noise)

# Calculating v_measure
print('v_measure =', v_measure_score(y, labels))

plt.figure(figsize=(12,8))
colors = ["navy", "turquoise", "darkorange"]
lw = 2

plt.scatter(
    X[cols_for_clusters[0]], X[cols_for_clusters[1]], c=dbscan_cluster1.labels_  # заменил cols на cols_for_clusters
)

plt.legend(loc="best", shadow=False, scatterpoints=2)
plt.xlabel("z1")
plt.ylabel("z2")
plt.show()

from sklearn.neighbors import NearestNeighbors

min_samples = 3

knn = NearestNeighbors(n_neighbors = min_samples, metric = 'l2')
knn.fit(X)

dists, inds = knn.kneighbors(X)
dists_ar = dists[:, 1:min_samples].mean(axis=1)
dists_ar.sort()

import sklearn
#возможные метрики расстояния
sklearn.metrics.pairwise.distance_metrics()

plt.scatter(x = range(len(dists_ar)), y=dists_ar)
plt.show()

"""# **DBSCAN для определения выбросов**"""

dbscan = DBSCAN(eps = 0.7, min_samples = min_samples)
print(dbscan)

pred = dbscan.fit_predict(X_scaled)

# Number of Clusters
labels=dbscan.labels_
N_clus=len(set(labels))-(1 if -1 in labels else 0)
print('Estimated no. of clusters: %d' % N_clus)

# Identify Noise
n_noise = list(dbscan.labels_).count(-1)
print('Estimated no. of noise points: %d' % n_noise)

# Calculating v_measure
print('v_measure =', v_measure_score(y, labels))

# у анномалий - класс -1, ищем все номера строк с таким классом, потом отбираем эти строки из начального набора данных

anom_index = np.where(pred == -1)[0]
values = X.iloc[anom_index]

plt.scatter( X[cols_for_clusters[0]], X[cols_for_clusters[1]],c=dbscan_cluster1.labels_)
plt.scatter(values[cols_for_clusters[0]], values[cols_for_clusters[1]], color='r')
plt.show()