# -*- coding: utf-8 -*-
"""ИИ энкодеры.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TT-ECgGQLfqwvUeV72WaXoPJtCVHF_DS

## Declare required dependencies
"""

import pandas as pd
import numpy as np
import pickle
import gdown
from torch.autograd import Variable
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
import torch.utils.data as data_utils
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
from pylab import rcParams
from sklearn.metrics import (confusion_matrix, precision_recall_curve, auc,
                             roc_curve, recall_score, classification_report, f1_score,
                             precision_recall_fscore_support)
sns.set(style='whitegrid', palette='muted', font_scale=1.5)
rcParams['figure.figsize'] = 14, 8
RANDOM_SEED = 42
LABELS = ["Regular", "Expensive"]

"""## Data ingestion from Google Drive

"""

file_id = "11W9D8NrZ0vQSh4tMEjZSIPFJ-XZhpJFY"
gdown.download(f'https://drive.google.com/uc?id={file_id}', 'diamonds.csv', quiet=False)

df = pd.read_csv('diamonds.csv')
unnamed_cols = [col for col in df.columns if col.lower().startswith('unnamed')]
if unnamed_cols:
    df = df.drop(columns=unnamed_cols)
df.head()

"""## Data exploration"""

df.head(5)

print(df.shape)
print(df.describe())

"""Ести ли пропуски?"""

df.isnull().values.any()

"""## Class distribution (Class: 0 - regular, 1 - expensive)

"""

price_threshold = df['price'].quantile(0.95)
df['Class'] = (df['price'] >= price_threshold).astype(int)
df['Class'].value_counts()

count_classes = pd.value_counts(df['Class'], sort=True)
count_classes.plot(kind='bar', rot=0, color="g")
plt.title("Regular vs Expensive Diamonds")
plt.xticks(range(2), LABELS)
plt.xlabel("Diamond Class")
plt.ylabel("Frequency");

"""Набор данных теперь тоже несбалансирован: дорогие бриллианты встречаются реже

"""

expensiveDF = df[df.Class == 1]
regularDF = df[df.Class == 0]

expensiveDF.shape

regularDF.shape

"""Посмотрим на распределение цены для двух классов.

"""

expensiveDF.price.describe()

regularDF.price.describe()

"""Сравним распределение price в обоих классах.

"""

f, (ax1, ax2) = plt.subplots(2, 1, sharex=True)
f.suptitle('Price per diamond by class')
bins = 50
ax1.hist(expensiveDF.price, bins=bins)
ax1.set_title('Expensive')
ax2.hist(regularDF.price, bins=bins)
ax2.set_title('Regular')
plt.xlabel('Price ($)')
plt.ylabel('Number of diamonds')
plt.yscale('log')
plt.show();

"""Посмотрим связь `carat` и `price` для двух классов.

"""

f, (ax1, ax2) = plt.subplots(2, 1, sharex=True)
f.suptitle('Carat vs Price by class')
ax1.scatter(expensiveDF.carat, expensiveDF.price)
ax1.set_title('Expensive')
ax2.scatter(regularDF.carat, regularDF.price)
ax2.set_title('Regular')
plt.xlabel('Carat')
plt.ylabel('Price')
plt.show()

"""Вместо временного признака здесь полезнее оставить все содержательные признаки и отдельно закодировать категориальные колонки.

## Preprocessing

Подготовим данные: создадим бинарную цель Class, закодируем категориальные признаки и стандартизируем числовые.
"""

transactionData = df.copy()
transactionData = pd.get_dummies(transactionData, columns=['cut', 'color', 'clarity'], drop_first=True)
transactionData = transactionData.drop(['price'], axis=1)

"""Стандартизируем все числовые признаки, кроме Class.

"""

feature_cols = [col for col in transactionData.columns if col != 'Class']
transactionData[feature_cols] = StandardScaler().fit_transform(transactionData[feature_cols])

"""### Разделите набор данных на наборы обучающих и тестовых данных.

Разделим данные на обучение = 80% и тест = 20%. В обучающем наборе будут только обычные бриллианты, а в тестовом — и обычные, и дорогие.

"""

X_train, X_test = train_test_split(
    transactionData, test_size=0.2, random_state=RANDOM_SEED, stratify=transactionData['Class']
)
X_train = X_train[X_train.Class == 0]
X_train = X_train.drop(['Class'], axis=1)
y_test = X_test['Class']
X_test = X_test.drop(['Class'], axis=1)
input_dim = X_train.shape[1]
encoding_dim = max(4, input_dim // 2)
bottleneck_dim = max(2, input_dim // 4)
X_train = X_train.values.astype(np.float64)
X_test = X_test.values.astype(np.float64)
y_test = y_test.values
print('input_dim =', input_dim)
print('test size =', y_test.size)

"""## Model
Построим автоэнкодер, где размер входа теперь вычисляется автоматически по числу признаков после кодирования категориальных столбцов.

"""

class Autoencoder(nn.Module):
    def __init__(self, input_dim, encoding_dim, bottleneck_dim):
        super(Autoencoder, self).__init__()
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, encoding_dim),
            nn.Tanh(),
            nn.Linear(encoding_dim, bottleneck_dim),
            nn.LeakyReLU(),
        )
        self.decoder = nn.Sequential(
            nn.Linear(bottleneck_dim, bottleneck_dim),
            nn.Tanh(),
            nn.Linear(bottleneck_dim, input_dim),
            nn.LeakyReLU(),
        )
    def forward(self, x):
        x = self.encoder(x)
        x = self.decoder(x)
        return x

model = Autoencoder(input_dim, encoding_dim, bottleneck_dim).double()

num_epochs = 100
minibatch_size = 32
learning_rate = 1e-3

"""**minibatch_size** - размер мини-пакета - это количество записей

**learning_rate** - скорость обучения.
"""

train_loader = data_utils.DataLoader(X_train, batch_size=minibatch_size, shuffle=True)

test_loader = data_utils.DataLoader(X_test, batch_size=1, shuffle=False)

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(
model.parameters(), lr=learning_rate, weight_decay=10e-05)

history = {}
history['train_loss'] = []
history['test_loss'] = []

for epoch in range(num_epochs):
    h = np.array([])
    for data in train_loader:
        output = model(data)
        loss = criterion(output, data)
        h = np.append(h, loss.item())
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    mean_loss = np.mean(h)
    print('epoch [{}/{}], loss:{:.4f}'.format(epoch + 1, num_epochs, mean_loss))
    history['train_loss'].append(mean_loss)
torch.save(model.state_dict(), './diamonds_autoencoder_model.pth')

plt.plot(history['train_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.axis([0,100,0.69,0.80])
plt.show()

"""## Оценка модели"""

pred_losses = {'pred_loss' : []}
model.eval()
with torch.no_grad():
    for data in test_loader:
        inputs = data
        outputs = model(inputs)
        loss = criterion(outputs, inputs).data.item()
        pred_losses['pred_loss'].append(loss)
reconstructionErrorDF = pd.DataFrame(pred_losses)
reconstructionErrorDF['Class'] = y_test

reconstructionErrorDF.describe()

reconstructionErrorDF.describe()

"""# Reconstruction Errors without Expensive class

"""

fig = plt.figure()
ax = fig.add_subplot(111)
normal_error_df = reconstructionErrorDF[(reconstructionErrorDF['Class'] == 0)]
_ = ax.hist(normal_error_df.pred_loss.values, bins=10)

"""# Reconstruction Errors with Expensive class

"""

fig = plt.figure()
ax = fig.add_subplot(111)
fraud_error_df = reconstructionErrorDF[(reconstructionErrorDF['Class'] == 1)]
_ = ax.hist(fraud_error_df.pred_loss.values, bins=10)

"""## ROC Curves"""

fpr, tpr, thresholds = roc_curve(reconstructionErrorDF.Class, reconstructionErrorDF.pred_loss)
roc_auc = auc(fpr, tpr)
plt.title('Receiver Operating Characteristic')
plt.plot(fpr, tpr, label='AUC = %0.4f'% roc_auc)
plt.legend(loc='lower right')
plt.plot([0,1],[0,1],'r--')
plt.xlim([-0.001, 1])
plt.ylim([0, 1.001])
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show();

"""## Precision vs Recall"""

precision, recall, th = precision_recall_curve(reconstructionErrorDF.Class, reconstructionErrorDF.pred_loss)
plt.plot(recall, precision, 'b', label='Precision-Recall curve')
plt.title('Recall vs Precision')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.show()

plt.plot(th, precision[1:], 'b', label='Threshold-Precision curve')
plt.title('Precision для разных значений трешхолда')
plt.xlabel('Threshold')
plt.ylabel('Precision')
plt.show()

"""Вы можете видеть, что по мере увеличения ошибки реконструкции повышается и наша precision. Давайте посмотрим на recall:

"""

plt.plot(th, recall[1:], 'b', label='Threshold-Recall curve')
plt.title('Recall для разных значений трешхолда')
plt.xlabel('Ошибка реконструкции')
plt.ylabel('Полнота (Recall)')
plt.show()

"""Здесь мы имеем прямо противоположную ситуацию. По мере увеличения ошибки реконструкции recall (полнота) уменьшается.

## Используем модель для того, чтобы сделать предсказание

Чтобы предсказать, относится ли новый бриллиант к редким дорогим объектам, будем использовать ошибку реконструкции. Если ошибка превышает выбранный порог, считаем объект аномалией.
"""

threshold = reconstructionErrorDF[reconstructionErrorDF['Class'] == 0]['pred_loss'].quantile(0.95)

groups = reconstructionErrorDF.groupby('Class')
fig, ax = plt.subplots()
for name, group in groups:
    ax.plot(group.index, group.pred_loss, marker='o', ms=3.5, linestyle='',
            label='Expensive' if name == 1 else 'Regular')
ax.hlines(threshold, ax.get_xlim()[0], ax.get_xlim()[1], colors='r', zorder=100, label='Threshold')
ax.legend()
plt.title("Ошибка реконструкции для разных классов")
plt.ylabel("Ошибка реконструкции")
plt.xlabel("Data point index")
plt.show();

"""Построим и посмотрим confusion matrix:"""

y_pred = [1 if e > threshold else 0 for e in reconstructionErrorDF.pred_loss.values]
conf_matrix = confusion_matrix(reconstructionErrorDF.Class, y_pred)
plt.figure(figsize=(12, 12))
sns.heatmap(conf_matrix, xticklabels=LABELS, yticklabels=LABELS, annot=True, fmt="d",
            cmap=plt.cm.get_cmap('Blues'));
plt.title("Confusion matrix")
plt.ylabel('True class')
plt.xlabel('Predicted class')
plt.show()

"""Модель показывает, насколько дорогие бриллианты отличаются от основной массы объектов по совокупности признаков. Порог можно менять, чтобы регулировать компромисс между ложными срабатываниями и полнотой.

# **Выводы**

Результаты:
*   Автоэнкодер успешно обучился восстанавливать «нормальные» объекты
*   Ошибка реконструкции выше для редких/дорогих алмазов
*   Метод можно использовать для поиска аномалий в табличных данных
"""