# -*- coding: utf-8 -*-
"""КТ разведочный анализ ИИ

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110zhaeTHxAiqp0CRFf7iRJ-F8mxUcSgc

# Волны жары в городах России

Датасет был взят с сайта: https://tochno.st/datasets/heatwaves
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler, StandardScaler
import seaborn as sns
sns.set()

sns.set(style='whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 10

import gdown

file_id = "1pIixR-an7ycdPeatkJLVG4MJAQMZEQDy"  # ID файла
gdown.download(f'https://drive.google.com/uc?id={file_id}', 'data_heatwaves_108_v20230923.csv', quiet=False)

heat = pd.read_csv('/content/data_heatwaves_108_v20230923.csv')

heat.head()

# удаляем пробелы в названиях столбцов
heat.columns = heat.columns.str.strip()

# проверяем названия столбцов
print("Названия столбцов")
print(heat.columns.tolist())

heat.describe()

heat.info()

heat.isnull().sum()

heat.city_meteoinfo.describe()

heat['city_meteoinfo'].sort_values().unique()

"""# Заполнение пропусков"""

heat.isnull().sum()

"""Пропусков нет

# Визуализация распределений и взаимосвязей

ВИЗУАЛИЗАЦИЯ ПО ОДНОМУ ПРИЗНАКУ
"""

plt.figure(figsize=(15, 8))
heat['region_name'].value_counts().plot(kind='bar', color='steelblue')
plt.title('Количество записей по регионам', fontsize=14, fontweight='bold')
plt.xlabel('Регион', fontsize=12)
plt.ylabel('Количество записей', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""Распределение городов (топ-20)"""

plt.figure(figsize=(15, 8))
heat['city'].value_counts().head(20).plot(kind='bar', color='coral')
plt.title('Топ-20 городов по количеству записей', fontsize=14, fontweight='bold')
plt.xlabel('Город', fontsize=12)
plt.ylabel('Количество записей', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""Распределение типов индикаторов"""

plt.figure(figsize=(10, 8))
heat['indicator_name'].value_counts().plot(kind='pie', autopct='%1.1f%%',
                                          colors=['#ff9999','#66b3ff','#99ff99'])
plt.title('Распределение типов индикаторов температуры', fontsize=14, fontweight='bold')
plt.ylabel('')
plt.tight_layout()
plt.show()

"""Распределение значений температуры (гистограмма)"""

plt.figure(figsize=(12, 6))
heat['indicator_value'].hist(bins=50, edgecolor='black', color='skyblue')
plt.title('Распределение значений температуры', fontsize=14, fontweight='bold')
plt.xlabel('Температура (°C)', fontsize=12)
plt.ylabel('Частота', fontsize=12)
plt.tight_layout()
plt.show()

"""Boxplot температурных значений"""

plt.figure(figsize=(10, 6))
heat.boxplot(column=['indicator_value'], patch_artist=True,
           boxprops=dict(facecolor='lightblue'))
plt.title('Boxplot распределения температур', fontsize=14, fontweight='bold')
plt.ylabel('Температура (°C)', fontsize=12)
plt.tight_layout()
plt.show()

"""Распределение по датам"""

heat['date'] = pd.to_datetime(heat['date'])
plt.figure(figsize=(15, 6))
heat['date'].value_counts().sort_index().plot(kind='line', color='green', linewidth=2)
plt.title('Количество записей по датам', fontsize=14, fontweight='bold')
plt.xlabel('Дата', fontsize=12)
plt.ylabel('Количество записей', fontsize=12)
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""Распределение индексов тепловых волн"""

plt.figure(figsize=(15, 8))
heat['heat_wave_index'].value_counts().head(20).plot(kind='bar', color='purple')
plt.title('Топ-20 индексов тепловых волн', fontsize=14, fontweight='bold')
plt.xlabel('Индекс тепловой волны', fontsize=12)
plt.ylabel('Количество записей', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""# Групповые визуализации

Температура по регионам
"""

plt.figure(figsize=(15, 8))
sns.boxplot(data=heat, x='region_name', y='indicator_value', palette='Set3')
plt.title('Распределение температур по регионам', fontsize=14, fontweight='bold')
plt.xlabel('Регион', fontsize=12)
plt.ylabel('Температура (°C)', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""Температура по типам индикаторов"""

plt.figure(figsize=(12, 15))
sns.boxplot(data=heat, x='indicator_name', y='indicator_value', palette='Set2')
plt.title('Распределение температур по типам индикаторов', fontsize=14, fontweight='bold')
plt.xlabel('Тип индикатора', fontsize=12)
plt.ylabel('Температура (°C)', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

""" Тепловая карта корреляции числовых признаков"""

plt.figure(figsize=(8, 6))
heat_numeric = heat[['region_okato', 'region_oktmo', 'indicator_value']].copy()
sns.heatmap(heat_numeric.corr(), annot=True, cmap='coolwarm', center=0,
            fmt='.2f', square=True, linewidths=1)
plt.title('Тепловая карта корреляции числовых признаков', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""Температура по месяцам"""

heat['month'] = heat['date'].dt.month
plt.figure(figsize=(12, 6))
sns.boxplot(data=heat, x='month', y='indicator_value', palette='viridis')
plt.title('Распределение температур по месяцам', fontsize=14, fontweight='bold')
plt.xlabel('Месяц', fontsize=12)
plt.ylabel('Температура (°C)', fontsize=12)
plt.tight_layout()
plt.show()

"""Countplot регионов с hue по типу индикатора"""

plt.figure(figsize=(15, 8))
sns.countplot(data=heat, x='region_name', hue='indicator_name', palette='Set1')
plt.title('Количество записей по регионам и типам индикаторов', fontsize=14, fontweight='bold')
plt.xlabel('Регион', fontsize=12)
plt.ylabel('Количество записей', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.legend(title='Тип индикатора', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""Температура по датам для разных регионов"""

plt.figure(figsize=(15, 8))
top_regions = heat['region_name'].value_counts().head(5).index
heat_top = heat[heat['region_name'].isin(top_regions)]
sns.scatterplot(data=heat_top, x='date', y='indicator_value',
                hue='region_name', palette='Dark2', s=100, alpha=0.7)
plt.title('Температура по датам для топ-5 регионов', fontsize=14, fontweight='bold')
plt.xlabel('Дата', fontsize=12)
plt.ylabel('Температура (°C)', fontsize=12)
plt.xticks(rotation=45)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""Температурa по регионам"""

plt.figure(figsize=(15, 8))
sns.violinplot(data=heat, x='region_name', y='indicator_value', palette='pastel')
plt.title('Violin plot распределения температур по регионам', fontsize=14, fontweight='bold')
plt.xlabel('Регион', fontsize=12)
plt.ylabel('Температура (°C)', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""Pairplot для числовых признаков"""

heat_pair = heat[['region_okato', 'indicator_value', 'month']].copy()
heat_pair = heat_pair.dropna()
sns.pairplot(heat_pair, hue='month', palette='viridis', diag_kind='hist')
plt.suptitle('Pairplot числовых признаков', y=1.02, fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""# Кодирование категориальных признаков"""

# Label Encoding для регионов
le_region = LabelEncoder()
heat['region_encoded'] = le_region.fit_transform(heat['region_name'])

# Label Encoding для городов
le_city = LabelEncoder()
heat['city_encoded'] = le_city.fit_transform(heat['city'])

# Label Encoding для типов индикаторов
le_indicator = LabelEncoder()
heat['indicator_encoded'] = le_indicator.fit_transform(heat['indicator_name'])

print(f"Уникальных регионов: {len(le_region.classes_)}")
print(f"Уникальных городов: {len(le_city.classes_)}")
print(f"Уникальных индикаторов: {len(le_indicator.classes_)}")

print("\nПример закодированных данных")
heat[['region_name', 'region_encoded', 'city', 'city_encoded',
    'indicator_name', 'indicator_encoded']].head(5)

"""ONE-HOT ENCODING"""

ohe = OneHotEncoder(sparse_output=False)
indicator_ohe = ohe.fit_transform(heat[['indicator_name']])
indicator_columns = ohe.get_feature_names_out(['indicator_name'])
heat_ohe = pd.DataFrame(indicator_ohe, columns=indicator_columns)
heat = pd.concat([heat.reset_index(drop=True), heat_ohe], axis=1)

print(f"Добавлено столбцов: {len(indicator_columns)}")
print("\nПример One-Hot Encoding")
heat[['indicator_name'] + list(indicator_columns)].head()

"""# Нормализация числовых признаков"""

# Мин-макс нормализация
scaler_mm = MinMaxScaler()
heat['indicator_value_norm'] = scaler_mm.fit_transform(heat[['indicator_value']])

# Z-нормализация (стандартизация)
scaler_std = StandardScaler()
heat['indicator_value_std'] = scaler_std.fit_transform(heat[['indicator_value']])

print(f"Мин-макс нормализация: min={heat['indicator_value_norm'].min():.3f}, max={heat['indicator_value_norm'].max():.3f}")
print(f"Z-нормализация: mean={heat['indicator_value_std'].mean():.3f}, std={heat['indicator_value_std'].std():.3f}")

print("\nПример нормализованных данных")
heat[['indicator_value', 'indicator_value_norm', 'indicator_value_std']].head(5)

# Визуализация нормализованных данных
fig, axs = plt.subplots(nrows=2, figsize=(15, 10))

sns.lineplot(data=heat.head(100), x=heat.index[:100], y='indicator_value', ax=axs[0], color='blue')
axs[0].set_title('Исходные значения температуры', fontsize=14, fontweight='bold')
axs[0].set_xlabel('Индекс записи', fontsize=12)
axs[0].set_ylabel('Температура (°C)', fontsize=12)
axs[0].grid(True, alpha=0.3)

sns.lineplot(data=heat.head(100), x=heat.index[:100], y='indicator_value_norm', ax=axs[1], color='green')
axs[1].set_title('Нормализованные значения температуры (Min-Max)', fontsize=14, fontweight='bold')
axs[1].set_xlabel('Индекс записи', fontsize=12)
axs[1].set_ylabel('Нормализованная температура', fontsize=12)
axs[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""# Выявление аномалий и выбросов"""

Q1 = heat['indicator_value'].quantile(0.25)
Q3 = heat['indicator_value'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = heat[(heat['indicator_value'] < lower_bound) | (heat['indicator_value'] > upper_bound)]

print(f"Q1 (25-й процентиль): {Q1:.2f}°C")
print(f"Q3 (75-й процентиль): {Q3:.2f}°C")
print(f"IQR: {IQR:.2f}°C")
print(f"Нижняя граница: {lower_bound:.2f}°C")
print(f"Верхняя граница: {upper_bound:.2f}°C")
print(f"\nКоличество выбросов: {len(outliers)} ({len(outliers)/len(heat)*100:.2f}%)")

if len(outliers) > 0:
    print(f"\nПримеры выбросов")
    print(outliers[['region_name', 'city', 'date', 'indicator_value', 'indicator_name']].head(10))

plt.figure(figsize=(12, 6))
sns.boxplot(data=heat, y='indicator_value')
plt.axhline(y=lower_bound, color='red', linestyle='--', label=f'Нижняя граница ({lower_bound:.1f}°C)')
plt.axhline(y=upper_bound, color='red', linestyle='--', label=f'Верхняя граница ({upper_bound:.1f}°C)')
plt.title('Выявление выбросов в температуре', fontsize=14, fontweight='bold')
plt.ylabel('Температура (°C)', fontsize=12)
plt.legend()
plt.tight_layout()
plt.show()

"""# Сводная статистика по регионам"""

region_stats = heat.groupby('region_name').agg({
    'indicator_value': ['mean', 'min', 'max', 'std'],
    'city': 'nunique',
    'date': ['min', 'max']
}).round(2)

print(region_stats)

# Топ-10 регионов по средней температуре
plt.figure(figsize=(12, 6))
top_temp_regions = heat.groupby('region_name')['indicator_value'].mean().sort_values(ascending=False).head(10)
sns.barplot(x=top_temp_regions.values, y=top_temp_regions.index, palette='YlOrRd')
plt.title('Топ-10 регионов по средней температуре', fontsize=14, fontweight='bold')
plt.xlabel('Средняя температура (°C)', fontsize=12)
plt.ylabel('Регион', fontsize=12)
plt.tight_layout()
plt.show()

"""# Итоговый отчёт"""

print(f"\n 1. ОБЪЁМ ДАННЫХ:")
print(f"    Всего записей: {len(heat)}")
print(f"    Всего столбцов: {len(heat.columns)}")
print(f"    Уникальных регионов: {heat['region_name'].nunique()}")
print(f"    Уникальных городов: {heat['city'].nunique()}")
print(f"    Уникальных индексов тепловых волн: {heat['heat_wave_index'].nunique()}")

print(f"\n 2. ДИАПАЗОН ДАТ:")
print(f"    Начало: {heat['date'].min()}")
print(f"    Конец: {heat['date'].max()}")
print(f"    Период: {(heat['date'].max() - heat['date'].min()).days} дней")

print(f"\n 3. ТЕМПЕРАТУРНЫЕ ПОКАЗАТЕЛИ:")
print(f"    Минимальная температура: {heat['indicator_value'].min():.2f}°C")
print(f"    Максимальная температура: {heat['indicator_value'].max():.2f}°C")
print(f"    Средняя температура: {heat['indicator_value'].mean():.2f}°C")
print(f"    Медиана: {heat['indicator_value'].median():.2f}°C")
print(f"    Стандартное отклонение: {heat['indicator_value'].std():.2f}°C")

print(f"\n 4. КАЧЕСТВО ДАННЫХ:")
print(f"    Пропущенные значения: {heat.isnull().sum().sum()}")
print(f"    Дубликаты: {heat.duplicated().sum()}")
print(f"    Выбросы: {len(outliers)} ({len(outliers)/len(heat)*100:.2f}%)")

print(f"\n 5. ТИПЫ ИНДИКАТОРОВ:")
for ind, count in heat['indicator_name'].value_counts().items():
    print(f"   • {ind}: {count} записей ({count/len(heat)*100:.1f}%)")

print(f"\n 6. РЕКОМЕНДАЦИИ:")
print(f"    Данные не содержат критических пропусков")
print(f"    Рекомендуется удалить выбросы при построении моделей")
print(f"    Категориальные признаки закодированы для ML")
print(f"    Числовые признаки нормализованы")
print(f"    Данные готовы для дальнейшего анализа и моделирования")