# -*- coding: utf-8 -*-
"""КТ Классификация ИИ

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110zhaeTHxAiqp0CRFf7iRJ-F8mxUcSgc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import warnings
warnings.filterwarnings('ignore')
sns.set()  # устанавливаем seaborn по умолчанию для отрисовки графиков

# Настройка стиля визуализаций
sns.set_style("whitegrid")
sns.set_palette("viridis")
plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['font.size'] = 12

import gdown

file_id = "12BgInyD1LJCNaAxEl4KNsXedvwpSbGpm"  # ID файла
gdown.download(f'https://drive.google.com/uc?id={file_id}', 'NPHA-doctor-visits.csv', quiet=False)

doc = pd.read_csv('/content/NPHA-doctor-visits.csv')

doc.head()

doc.describe()

print("\n" + "="*80)
print("2. ИНФОРМАЦИЯ О ДАТАФРЕЙМЕ (метод .info())")
print("="*80)
doc.info()

print("\n" + "="*80)
print("3. СТАТИСТИЧЕСКОЕ ОПИСАНИЕ ЧИСЛОВЫХ ПРИЗНАКОВ (.describe())")
print("="*80)
print(doc.describe().T)

print("\n" + "="*80)
print("4. НАЗВАНИЯ СТОЛБЦОВ И РАЗМЕРНОСТЬ")
print("="*80)
print(f"Названия столбцов:\n{list(doc.columns)}")
print(f"\nКоличество строк: {doc.shape[0]}")
print(f"Количество столбцов: {doc.shape[1]}")

print("\n" + "="*80)
print("5. ПРОПУЩЕННЫЕ ЗНАЧЕНИЯ И УНИКАЛЬНЫЕ ЗНАЧЕНИЯ КАТЕГОРИАЛЬНЫХ ПРИЗНАКОВ")
print("="*80)
print("Пропущенные значения:")
print(doc.isnull().sum())

print("\nУникальные значения для потенциально категориальных признаков:")
categorical_cols = ['Race', 'Gender', 'Employment', 'Prescription Sleep Medication', 'Trouble Sleeping']
for col in categorical_cols:
    print(f"\n{col}: {sorted(doc[col].unique())}")

# Создание словарей для декодирования категориальных переменных
race_mapping = {
    1: 'White',
    2: 'Black/African American',
    3: 'Asian',
    4: 'Native American',
    5: 'Hispanic/Latino',
    -1: 'Unknown/Other'
}
gender_mapping = {
    1: 'Male',
    2: 'Female',
    -1: 'Other/Unknown'
}

employment_mapping = {
    1: 'Unemployed',
    2: 'Part-time',
    3: 'Full-time',
    4: 'Student'
}

sleep_med_mapping = {
    1: 'None',
    2: 'Over-the-counter',
    3: 'Prescription',
    -1: 'Unknown'
}

trouble_sleeping_mapping = {
    1: 'Rarely',
    2: 'Sometimes',
    3: 'Often/Always'
}

# Создание копии датафрейма с декодированными значениями для визуализации
df_decoded = doc.copy()
df_decoded['Race_Decoded'] = doc['Race'].map(race_mapping)
df_decoded['Gender_Decoded'] = doc['Gender'].map(gender_mapping)
df_decoded['Employment_Decoded'] = doc['Employment'].map(employment_mapping)
df_decoded['Sleep_Med_Decoded'] = doc['Prescription Sleep Medication'].map(sleep_med_mapping)
df_decoded['Trouble_Sleeping_Decoded'] = doc['Trouble Sleeping'].map(trouble_sleeping_mapping)

print("\n" + "="*80)
print("6. ЗАМЕНА КАТЕГОРИАЛЬНЫХ ДАННЫХ НА КОЛИЧЕСТВЕННЫЕ (ДЕКОДИРОВАНИЕ)")
print("="*80)
print("Создан новый датафрейм df_decoded с читаемыми категориями для визуализации")
print("\nПример декодированных данных:")
print(df_decoded[['Race_Decoded', 'Gender_Decoded', 'Employment_Decoded',
                  'Sleep_Med_Decoded', 'Trouble_Sleeping_Decoded']].head(3))

"""# ==============================================================
#                       ВИЗУАЛИЗАЦИИ
# ==============================================================
"""

# 1. Распределение количества посещений врачей (2 визуализации)
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

sns.histplot(doc['Number of Doctors Visited'], bins=10, kde=True, ax=axes[0], color='skyblue')
axes[0].set_title('Распределение количества посещений врачей', fontsize=16, fontweight='bold')
axes[0].set_xlabel('Количество посещений')
axes[0].set_ylabel('Частота')

sns.boxplot(data=doc, x='Number of Doctors Visited', ax=axes[1], palette='Set2')
axes[1].set_title('Ящик с усами: Посещения врачей', fontsize=16, fontweight='bold')
axes[1].set_xlabel('Количество посещений')

plt.tight_layout()
plt.savefig('visits_distribution.png', dpi=300, bbox_inches='tight')
plt.show()

# 2. Физическое и ментальное здоровье (2 визуализации)
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

health_data = doc[['Phyiscal Health', 'Mental Health', 'Dental Health']].melt(var_name='Health Type', value_name='Score')
sns.violinplot(data=health_data, x='Health Type', y='Score', ax=axes[0], palette='magma')
axes[0].set_title('Распределение показателей здоровья', fontsize=16, fontweight='bold')
axes[0].set_xticklabels(['Физическое', 'Ментальное', 'Стоматологическое'], rotation=15)

sns.scatterplot(data=doc, x='Phyiscal Health', y='Mental Health', hue='Number of Doctors Visited',
                palette='viridis', s=100, alpha=0.7, ax=axes[1])
axes[1].set_title('Корреляция физического и ментального здоровья', fontsize=16, fontweight='bold')
axes[1].set_xlabel('Физическое здоровье')
axes[1].set_ylabel('Ментальное здоровье')
axes[1].legend(title='Посещения врачей', bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()
plt.savefig('health_comparison.png', dpi=300, bbox_inches='tight')
plt.show()

# 3. Проблемы со сном - причины (2 визуализации)
sleep_reasons = ['Stress Keeps Patient from Sleeping', 'Medication Keeps Patient from Sleeping',
                 'Pain Keeps Patient from Sleeping', 'Bathroom Needs Keeps Patient from Sleeping',
                 'Uknown Keeps Patient from Sleeping']

sleep_sum = doc[sleep_reasons].sum().sort_values(ascending=False)
sleep_sum.index = ['Стресс', 'Медикаменты', 'Боль', 'Туалет', 'Неизвестно']

fig, axes = plt.subplots(1, 2, figsize=(18, 6))

# Гистограмма
sns.barplot(x=sleep_sum.index, y=sleep_sum.values, ax=axes[0], palette='rocket')
axes[0].set_title('Основные причины проблем со сном', fontsize=16, fontweight='bold')
axes[0].set_ylabel('Количество случаев')
axes[0].set_xlabel('Причина')

# Круговая диаграмма
colors = sns.color_palette('rocket', len(sleep_sum))
axes[1].pie(sleep_sum.values, labels=sleep_sum.index, autopct='%1.1f%%', colors=colors,
            startangle=90, explode=[0.05]*len(sleep_sum))
axes[1].set_title('Структура причин проблем со сном', fontsize=16, fontweight='bold')

plt.tight_layout()
plt.savefig('sleep_reasons.png', dpi=300, bbox_inches='tight')
plt.show()

"""# =================================================================
# ГРУППОВЫЕ ВИЗУАЛИЗАЦИИ (минимум 3)
# =================================================================
"""

# Групповая визуализация 1: Количество посещений врачей по расе и полу
plt.figure(figsize=(14, 8))
sns.boxplot(data=df_decoded, x='Race_Decoded', y='Number of Doctors Visited',
            hue='Gender_Decoded', palette='Set1')
plt.title('Количество посещений врачей по расе и полу', fontsize=18, fontweight='bold', pad=20)
plt.xlabel('Раса', fontsize=14)
plt.ylabel('Количество посещений', fontsize=14)
plt.xticks(rotation=15)
plt.legend(title='Пол', fontsize=12)
plt.tight_layout()
plt.savefig('visits_by_race_gender.png', dpi=300, bbox_inches='tight')
plt.show()

# Групповая визуализация 2: Тепловая карта корреляций числовых признаков
plt.figure(figsize=(14, 10))
numeric_cols = ['Number of Doctors Visited', 'Age', 'Phyiscal Health', 'Mental Health',
                'Dental Health', 'Trouble Sleeping']
corr_matrix = doc[numeric_cols].corr()

mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm',
            square=True, mask=mask, linewidths=0.5, annot_kws={"size": 12})
plt.title('Тепловая карта корреляций ключевых признаков', fontsize=18, fontweight='bold', pad=20)
plt.tight_layout()
plt.savefig('correlation_heatmap.png', dpi=300, bbox_inches='tight')
plt.show()

# Групповая визуализация 3: Сетчатая диаграмма (Radar Chart) для разных групп занятости
employment_groups = df_decoded.groupby('Employment_Decoded')[['Phyiscal Health', 'Mental Health', 'Dental Health']].mean()

# Нормализация для лучшей визуализации
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
employment_norm = pd.DataFrame(
    scaler.fit_transform(employment_groups),
    index=employment_groups.index,
    columns=employment_groups.columns
)

categories = list(employment_norm.columns)
N = len(categories)

angles = [n / float(N) * 2 * np.pi for n in range(N)]
angles += angles[:1]

fig, ax = plt.subplots(figsize=(10, 10), subplot_kw=dict(projection='polar'))

for idx, row in employment_norm.iterrows():
    values = row.values.tolist()
    values += values[:1]
    ax.plot(angles, values, 'o-', linewidth=2, label=idx)
    ax.fill(angles, values, alpha=0.15)

ax.set_xticks(angles[:-1])
ax.set_xticklabels(categories, size=14)
ax.set_ylim(0, 1)
ax.set_title('Сравнение здоровья по типу занятости', size=18, fontweight='bold', pad=30)
ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1), fontsize=12)
ax.grid(True)

plt.tight_layout()
plt.savefig('radar_employment_health.png', dpi=300, bbox_inches='tight')
plt.show()

# Групповая визуализация 4 (дополнительная): Взаимосвязь проблем со сном и посещений врачей
fig, axes = plt.subplots(2, 2, figsize=(16, 14))

# 1. Посещения врачей по уровню проблем со сном
sns.barplot(data=df_decoded, x='Trouble_Sleeping_Decoded', y='Number of Doctors Visited',
            ax=axes[0, 0], palette='Blues_d')
axes[0, 0].set_title('Посещения врачей по частоте проблем со сном', fontsize=14, fontweight='bold')
axes[0, 0].set_xlabel('Частота проблем со сном')
axes[0, 0].set_ylabel('Среднее количество посещений')

# 2. Тип снотворного и посещения врачей
sns.boxplot(data=df_decoded, x='Sleep_Med_Decoded', y='Number of Doctors Visited',
            ax=axes[0, 1], palette='Greens_d')
axes[0, 1].set_title('Посещения врачей по типу снотворного', fontsize=14, fontweight='bold')
axes[0, 1].set_xlabel('Тип снотворного')
axes[0, 1].set_ylabel('Количество посещений')
axes[0, 1].tick_params(axis='x', rotation=15)

# 3. Причины проблем со сном по полу
sleep_by_gender = df_decoded.melt(id_vars='Gender_Decoded',
                                  value_vars=['Stress Keeps Patient from Sleeping',
                                              'Pain Keeps Patient from Sleeping',
                                              'Bathroom Needs Keeps Patient from Sleeping'],
                                  var_name='Reason', value_name='Count')
sleep_by_gender = sleep_by_gender[sleep_by_gender['Count'] == 1]
sleep_by_gender['Reason'] = sleep_by_gender['Reason'].map({
    'Stress Keeps Patient from Sleeping': 'Стресс',
    'Pain Keeps Patient from Sleeping': 'Боль',
    'Bathroom Needs Keeps Patient from Sleeping': 'Туалет'
})

sns.countplot(data=sleep_by_gender, x='Reason', hue='Gender_Decoded', ax=axes[1, 0], palette='Set2')
axes[1, 0].set_title('Причины проблем со сном по полу', fontsize=14, fontweight='bold')
axes[1, 0].set_ylabel('Количество случаев')

# 4. Взаимосвязь физического здоровья и проблем со сном
sns.violinplot(data=df_decoded, x='Trouble_Sleeping_Decoded', y='Phyiscal Health',
               hue='Gender_Decoded', split=True, ax=axes[1, 1], palette='Set1')
axes[1, 1].set_title('Физическое здоровье vs Проблемы со сном', fontsize=14, fontweight='bold')
axes[1, 1].set_xlabel('Частота проблем со сном')
axes[1, 1].set_ylabel('Физическое здоровье')

plt.suptitle('Комплексный анализ взаимосвязи сна и здоровья', fontsize=18, fontweight='bold', y=0.995)
plt.tight_layout()
plt.savefig('sleep_health_analysis.png', dpi=300, bbox_inches='tight')
plt.show()

"""# ================================================================
# ИТОГОВАЯ СТАТИСТИКА
# ================================================================
"""

print("\n" + "="*80)
print("7. КЛЮЧЕВЫЕ ИНСАЙТЫ ИЗ АНАЛИЗА")
print("="*80)
print(f"• Среднее количество посещений врачей: {doc['Number of Doctors Visited'].mean():.2f}")
print(f"• Медианное физическое здоровье: {doc['Phyiscal Health'].median()}")
print(f"• Медианное ментальное здоровье: {doc['Mental Health'].median()}")
print(f"• Самая частая причина проблем со сном: Стресс ({doc['Stress Keeps Patient from Sleeping'].sum()} случаев)")
print(f"• Доля пациентов с сильными проблемами со сном (оценка 3): {(doc['Trouble Sleeping'] == 3).sum() / len(doc) * 100:.1f}%")
print(f"• Самая распространенная раса в выборке: {df_decoded['Race_Decoded'].value_counts().idxmax()}")
print(f"• Соотношение мужчин/женщин: {doc['Gender'].value_counts().get(1, 0)} / {doc['Gender'].value_counts().get(2, 0)}")

print("\n✅ Анализ завершен! Все визуализации сохранены как PNG-файлы с высоким разрешением.")